/**
 * Assembly instance editor.
 *
 * @asset(ncms/icon/16/actions/core_link.png)
 */
qx.Class.define("ncms.asm.AsmEditor", {
    extend : qx.ui.core.Widget,

    statics : {
    },

    events : {
    },

    properties : {

        /**
         * Assembly ID to load in editor
         */
        "asmId" : {
            apply : "__applyAsmId",
            nullable : false,
            check : "Number"
        },

        /**
         * Set assembly JSON representation
         * ofcom.softmotions.ncms.asm.Asm
         */
        "asmSpec" : {
            apply : "__applyAsmSpec",
            nullable : false,
            check : "Object"
        }
    },

    construct : function() {
        this.base(arguments);
        this._setLayout(new qx.ui.layout.VBox());

        var app = ncms.Application.INSTANCE;
        var form = this.__form = new qx.ui.form.Form();
        var vmgr = form.getValidationManager();
        vmgr.setRequiredFieldMessage(this.tr("This field is required"));

        var el = new qx.ui.form.TextField();
        el.setRequired(true);
        form.add(el, this.tr("Name"), null, "name");

        el = new sm.ui.form.ButtonField(null, "ncms/icon/16/actions/core_link.png");
        el.setReadOnly(true);
        form.add(el, this.tr("Core"), null, "core");

        el = new ncms.asm.AsmParentsTable();
        form.add(el, this.tr("Parents"), null, "parents");

        el = new ncms.asm.AsmAttrsTable();
        form.add(el, this.tr("Attributes"), null, "attributes");

        form.addButton(new qx.ui.form.Button(this.tr("Save")));

        var fr = new sm.ui.form.FlexFormRenderer(form);
        fr.setAppearance("ncms-wsa-form");
        this._add(fr);
    },

    members : {

        __form : null,

        __applyAsmId : function(value, old) {
            qx.log.Logger.info("Edit asm ID =" + value);
            var req = new sm.io.Request(
                    ncms.Application.ACT.getRestUrl("asms.get", value),
                    "GET", "application/json");
            req.send(function(resp) {
                var asmSpec = resp.getContent();
                this.setAsmSpec(asmSpec);
            }, this);
        },


//     Sample assembly spec generated by:com.softmotions.ncms.adm.AsmEditorRS
//
//            {
//                "id" : 3,
//                "name" : "pub.content",
//                "type" : null,
//                "description" : null,
//                "options" : null,
//                "parentRefs" : ["2:pub.main"],
//                "core" : null,
//                "effectiveCore" : {
//                    "id" : 1,
//                    "location" : "foo/bar",
//                    "name" : "fobarcore",
//                    "templateEngine" : null
//                },
//                "effectiveAttributes" : [
//                    {
//                        "asmId" : 1,
//                        "name" : "copyright",
//                        "type" : "string",
//                        "value" : "My company (c)",
//                        "options" : null,
//                        "hasLargeValue" : false
//                    },
//                    {
//                        "asmId" : 1,
//                        "name" : "title",
//                        "type" : "string",
//                        "value" : "Hello world",
//                        "options" : null,
//                        "hasLargeValue" : false
//                    },
//                    {
//                        "asmId" : 3,
//                        "name" : "content",
//                        "type" : "string",
//                        "value" : "Simple text",
//                        "options" : null,
//                        "hasLargeValue" : false
//                    }
//                ]
//            }

        __applyAsmSpec : function(spec) {
            qx.log.Logger.info("spec=" + JSON.stringify(spec));
        }
    },

    destruct : function() {
        this.__form = null;
    }
});