/**
 * User instance editor.
 *
 *
 *
 * Sample assembly spec generated by:com.softmotions.ncms.adm.AsmEditorRS
 *
 * {"name":"admin",
 *  "email":"adamansky@gmail.com",
 *  "fullName":"Адаманский Антон"
 * }
 *
 * @asset(ncms/icon/16/actions/core_link.png)
 */
qx.Class.define("ncms.usr.editor.UserEditor", {
    extend : qx.ui.core.Widget,

    statics : {
    },

    events : {
    },

    properties : {

        /**
         * Assembly ID to load in editor
         */
        "userId" : {
            apply : "__applyUserId",
            nullable : true,
            check : "Number"
        }

    },

    construct : function() {
    	alert("UserEditor started");
        this.base(arguments);
        this._setLayout(new qx.ui.layout.VBox());

        var el = new ncms.usr.editor.UserRolesTable();
        el.setUser("dimad");

        this._add(el);
    },

    members : {
        __applyUserId : function(value, old) {
            if (value == null) {
                this.setRoleSpec(null);
                return;
            }
            this.__reload();
        },
    	
        __reload : function() {
            var req = new sm.io.Request(
                    ncms.Application.ACT.getRestUrl("roles", {id : this.getName()}),
                    "GET", "application/json");
            req.send(function(resp) {
                var roleSpec = resp.getContent();
                //Prevent overiding of non related form values in `__applyUserSpec`
                // if we loading the specific 'part' of data
                this.setRoleSpec(roleSpec);
            }, this);
        }
    },

    destruct : function() {
        this._disposeObjects("__form");
    }
});